apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiops-demo
  template:
    metadata:
      labels:
        app: aiops-demo
    spec:
      containers:
      - name: app
        image: aiops-demo
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "500m"